"""initial schema

Revision ID: 8699cdd30e31
Revises: 
Create Date: 2026-08-11 06:29:30.239128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('ats', sa.String(length=50), nullable=True),
    sa.Column('board_token', sa.String(length=255), nullable=True),
    sa.Column('career_url', sa.String(length=500), nullable=True),
    sa.Column('collection_status', sa.String(length=50), nullable=False),
    sa.Column('strategic_themes', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_successful_check', sa.DateTime(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('source_health', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('source_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('run_started_at', sa.DateTime(), nullable=False),
    sa.Column('run_finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_source'), 'source_health', ['source'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=False),
    sa.Column('normalized_job_title', sa.String(length=500), nullable=False),
    sa.Column('role_family', sa.String(length=100), nullable=True),
    sa.Column('opportunity_class', sa.String(length=50), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('job_description_raw', sa.Text(), nullable=True),
    sa.Column('job_description_clean', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('required_experience', sa.String(length=500), nullable=True),
    sa.Column('education_requirements', sa.JSON(), nullable=False),
    sa.Column('certification_requirements', sa.JSON(), nullable=False),
    sa.Column('language_requirements', sa.JSON(), nullable=False),
    sa.Column('security_clearance_requirements', sa.JSON(), nullable=False),
    sa.Column('location_raw', sa.String(length=500), nullable=True),
    sa.Column('remote_classification', sa.String(length=60), nullable=False),
    sa.Column('location_eligibility', sa.String(length=20), nullable=False),
    sa.Column('required_residence_countries', sa.JSON(), nullable=False),
    sa.Column('permitted_residence_countries', sa.JSON(), nullable=False),
    sa.Column('excluded_residence_countries', sa.JSON(), nullable=False),
    sa.Column('timezone_requirements', sa.String(length=255), nullable=True),
    sa.Column('travel_required', sa.Boolean(), nullable=False),
    sa.Column('travel_frequency', sa.String(length=255), nullable=True),
    sa.Column('travel_destinations', sa.JSON(), nullable=False),
    sa.Column('physical_office_requirement', sa.Boolean(), nullable=False),
    sa.Column('office_country', sa.String(length=100), nullable=True),
    sa.Column('work_authorization_required', sa.Boolean(), nullable=False),
    sa.Column('visa_requirements', sa.String(length=500), nullable=True),
    sa.Column('us_presence_required', sa.Boolean(), nullable=False),
    sa.Column('thailand_presence_required', sa.Boolean(), nullable=False),
    sa.Column('candidate_geographically_eligible', sa.String(length=20), nullable=False),
    sa.Column('geographic_evidence', sa.JSON(), nullable=False),
    sa.Column('geographic_confidence', sa.Float(), nullable=False),
    sa.Column('salary_raw', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=30), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_candidate_geographically_eligible'), 'jobs', ['candidate_geographically_eligible'], unique=False)
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_job_title'), 'jobs', ['normalized_job_title'], unique=False)
    op.create_index(op.f('ix_jobs_remote_classification'), 'jobs', ['remote_classification'], unique=False)
    op.create_index(op.f('ix_jobs_role_family'), 'jobs', ['role_family'], unique=False)
    op.create_table('application_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_contact', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('reaction', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gigs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('advertised_hourly_rate_min', sa.Float(), nullable=True),
    sa.Column('advertised_hourly_rate_max', sa.Float(), nullable=True),
    sa.Column('rate_currency', sa.String(length=10), nullable=True),
    sa.Column('expected_weekly_hours_min', sa.Float(), nullable=True),
    sa.Column('expected_weekly_hours_max', sa.Float(), nullable=True),
    sa.Column('project_duration', sa.String(length=255), nullable=True),
    sa.Column('residency_countries', sa.JSON(), nullable=False),
    sa.Column('qualification_requirements', sa.JSON(), nullable=False),
    sa.Column('specialist_classification', sa.String(length=100), nullable=True),
    sa.Column('gig_quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_version', sa.String(length=20), nullable=False),
    sa.Column('remote_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('skills_score', sa.Float(), nullable=False),
    sa.Column('training_advantage_score', sa.Float(), nullable=False),
    sa.Column('ai_cyber_intersection_score', sa.Float(), nullable=False),
    sa.Column('interview_probability_score', sa.Float(), nullable=False),
    sa.Column('compensation_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('strategic_company_bonus', sa.Float(), nullable=False),
    sa.Column('can_do_score', sa.Float(), nullable=False),
    sa.Column('desirability_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=40), nullable=False),
    sa.Column('mandatory_mismatches', sa.JSON(), nullable=False),
    sa.Column('preferred_gaps', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('concerns', sa.JSON(), nullable=False),
    sa.Column('geographic_evidence', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('application_readiness', sa.String(length=40), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analysis_overall_score'), 'job_analysis', ['overall_score'], unique=False)
    op.create_index(op.f('ix_job_analysis_recommendation'), 'job_analysis', ['recommendation'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('quality_rank', sa.Integer(), nullable=False),
    sa.Column('source_published_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_usage')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_job_analysis_recommendation'), table_name='job_analysis')
    op.drop_index(op.f('ix_job_analysis_overall_score'), table_name='job_analysis')
    op.drop_table('job_analysis')
    op.drop_table('gigs')
    op.drop_table('feedback')
    op.drop_table('application_status')
    op.drop_index(op.f('ix_jobs_role_family'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_remote_classification'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_job_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_candidate_geographically_eligible'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_source_health_source'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
